### ISSUE TITLE
How to add hasttags

### ISSUE THREAD

**Issue by Yannicko** [FreekBes/insta_reddit_bot#1]
How do I make it so that it adds hashtags instead of saying from which subreddit / reddit user it mirrored the post from? This would be really great if it works. Your bot is the only one that I've found that's working, big ups to you!

**Comment by FreekBes** [comment]
To add hashtags or any other text to the caption, modify the following code in main.js:
on line 98 (`let tempExtraCaption = `) before the closing semicolon (`;`), add the following: ` + " \u2063\n\u2063\n#hashtag #hashtag2 anyothertext"`.

An example:

`let tempExtraCaption = "\u2063\n\u2063\nMirrored from a post on " + redditor.getSubreddit() + " by /u/" + post['data']['author'] + ": http://redd.it/" + post['data']['id'] + " \u2063\n\u2063\n#hashtag #hashtag2 anyothertext";`

**Comment by Yannicko** [comment]
You're a legend!

**Comment by Yannicko** [comment]
Could you please give me advice on which Raspberry PI version is the best fit to run bots like these?

**Comment by hugovantriet** [comment]
> 
> 
> Could you please give me advice on which Raspberry PI version is the best fit to run bots like these?

This is not a very demending program, so even the cheapest raspberry pi should do.
So the pi zero w should do it, but I would recommend to use at least one with a ethernet port, for more stability.
