### ISSUE TITLE
imgur image links.

### ISSUE THREAD

**Issue by Laezor** [FreekBes/insta_reddit_bot#10]
I see that when it finds an imgur image link it will try to retrieve the url image but in the end it gets stuck. Is it fixable?
![image](https://user-images.githubusercontent.com/32393101/101150583-1d6a5900-3629-11eb-9b20-7dd74e43fab2.png)

**Comment by FreekBes** [comment]
How does it get stuck? Does it quit the script with an error, or does it just freeze?
The [image link](https://i.imgur.com/GzcK11e.jpg) seems to be correct.

**Comment by Laezor** [comment]
it stucks at that point when it finds an imgur link. It doesnt stop and no errors.

**Comment by FreekBes** [comment]
Found the issue, it seems that Imgur has finally decided to move away from HTTP.

Fixed in commit 134f14320c1cf2356a37369eee9d5bb368d87b3d
