### ISSUE TITLE
Bot crashes when its trying to upload video

### ISSUE THREAD

**Issue by williamzerner** [FreekBes/insta_reddit_bot#13]
happens everytime its trying to upload video
[AVIOContext @ 0000022a313390c0] Statistics: 131072 bytes read, 0 seeks
Conversion failed!

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

**Comment by FreekBes** [comment]
Can you upload more of the logs outputted when trying to upload a video? Or is this all it returns?

**Comment by williamzerner** [comment]
This is the main error rest of it is just the ffmpeg commands that were executed.

**Comment by FreekBes** [comment]
It seems to be an issue with ffmpeg filters, probably specific to Windows. Could you try and modify the -vf argument in de ffmpeg command to use " instead of ', and let me know if it works then?

**Comment by williamzerner** [comment]
okay i replaced the ' to ". Also i had to add an extra " as one of the variable was not considered.

**Comment by FreekBes** [comment]
Oh sorry, I forgot about escaping. Use `\"` instead of `'`, so `command = "ffmpeg -loglevel verbose -analyzeduration 20M -probesize 20M -y -re -i " + downloadLoc + " -vcodec libx264 -b:v 3500k -vsync 2 -t 59 -acodec aac -b:a 128k -pix_fmt yuv420p -vf \"scale=1080:1080:force_original_aspect_ratio=decrease,pad=1080:1080:(ow-iw)/2:(oh-ih)/2:white\" " + convertLoc;`

**Comment by williamzerner** [comment]
I removed ' and it worked fine...this I had done before you gave the above solution. I havent ran into any error. In case i do i will use your solution. Thank you

**Comment by FreekBes** [comment]
If the issue reappears, please reopen it! Glad to hear it's now working fine.
