### ISSUE TITLE
After running the bot for a while, it cannot post the credits.

### ISSUE THREAD

**Issue by 1Legend11** [FreekBes/insta_reddit_bot#16]
Could not comment credits!
IgActionSpamError: POST /api/v1/media/2616282449558430455_48796745130/comment/ - 400 Bad Request; feedback_required
    at Request.handleResponseError (/home/legend/Desktop/bot1/node_modules/instagram-private-api/dist/core/request.js:99:20)
    at Request.send (/home/legend/Desktop/bot1/node_modules/instagram-private-api/dist/core/request.js:53:28)

It works at first on a new account, then after a while I get that error.

**Comment by FreekBes** [comment]
I am currently getting the same error. Normally, with a `feedback_required` error, you have to open Instagram on the web or the app to confirm something. However, in this case nothing pops up. I have no solution thus far, and will let you know if I find anything.

If anyone else reading this is experiencing the same problem and has something helpful to share, please do leave a comment.

**Comment by 1Legend11** [comment]
Yes anyone please help!

**Comment by williamzerner** [comment]
Open the account on phone/pc . One of the posts might have violated the guidelines like spam.  Just accept that "this post has been removed for " so and so reason. This has to be done manually. After you have accepted the warning just exit and restart the bot. I have got it so many times.

**Comment by williamzerner** [comment]
I also figured out that sometimes the bot posts twice(two different posts) in the same minute, which is specified in settings.json which should not be possible.

**Comment by FreekBes** [comment]
There is no mention of a removed post in the app or the website in this case. Normally, posting would not be possible with a `feedback_required` error, but in this case it's only commenting which doesn't work (a caption is basically a comment).

Also, @williamzerner, for the double post issue, check if the bot is only running in a single instance. If not, please open a new issue for it.

**Comment by FreekBes** [comment]
A solution has been found! Do the following:

Stop the bot by pressing <kbd>Ctrl</kbd>+<kbd>C</kbd>. Run the following command: `rm handlers/cookies.json` (which deletes the bot's cookies).

Then modify *settings.json*'s `seed` value under `instagram` (line 5) to a different string (do keep the quotation marks). Restart the bot with the `node bot.js` command and it should work again!

If the `credits_in_caption` value was previously set to `false`, change it to `true`. This might help in the future in terms of bot detection. By default, the value is `true`.
