### ISSUE TITLE
am getting this issue can u help he sorting it out

### ISSUE THREAD

**Issue by shrimantagarain** [FreekBes/insta_reddit_bot#18]
Post added to done-list
Downloading media...Initial mediaUrl:  https://v.redd.it/odjwdtp6d8k71
GIFV on Imgur detected
(node:12780) UnhandledPromiseRejectionWarning: https://ffmpeg.org/download.html to enable support for video posts.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12780) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12780) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by FreekBes** [comment]
For video support you need to download and install ffmpeg from the link provided in the error message you sent. Make sure it works in the command line (test with `ffmpeg -v`)

**Comment by shrimantagarain** [comment]
sir , all the insta posts are getting these comments "Mirrored from a post on /r/IndianDankMemes by /u/rb_kishore: https://redd.it/pdsalb" is there any way to remove these comments? 
will be very thankfull is u help!

**Comment by shrimantagarain** [comment]
ffmpeg is installed to my path still it getting the same error

input: ffmpeg -v

Output: 

PS D:\New folder (2)\tarunbot> ffmpeg -v
ffmpeg version 4.4-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100  libavdevice    58. 13.100 / 58. 13.100  libavfilter     7.110.100 /  7.110.100  libswscale      5.  9.100 /  5.  9.100  libswresample   3.  9.100 /  3.  9.100  libpostproc    55.  9.100 / 55.  9.100Missing argument for option 'v'.
Error splitting the argument list: Invalid argument
