### ISSUE TITLE
am getting issue related ytdl dwnld plz help

### ISSUE THREAD

**Issue by shrimantagarain** [FreekBes/insta_reddit_bot#19]
Downloading media...
Initial mediaUrl:  https://v.redd.it/xvsj09u6i9k71
GIFV on Imgur detected
YT-DL URL:  https://www.reddit.com/r/videomemes/comments/pdrwpb/crabs_fucking_die_emotional/
youtube-dl -o D:\New folder (2)\tarunbot\temp\pdrwpb-temp.mp4 https://www.reddit.com/r/videomemes/comments/pdrwpb/crabs_fucking_die_emotional/
(node:15756) UnhandledPromiseRejectionWarning: Error: Command failed: youtube-dl -o D:\New folder (2)\tarunbot\temp\pdrwpb-temp.mp4 https://www.reddit.com/r/videomemes/comments/pdrwpb/crabs_fucking_die_emotional/
**ERROR: fixed output name but more than one file to download**

    at ChildProcess.exithandler (child_process.js:390:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15756) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by FreekBes** [comment]
Try removing the space from the "New folder" name. Let me know if that fixes the issue

**Comment by shrimantagarain** [comment]
thanks a lot, sir it's all working now...
