### ISSUE TITLE
Crontab not working

### ISSUE THREAD

**Issue by Yannicko** [FreekBes/insta_reddit_bot#2]
![image](https://user-images.githubusercontent.com/32157860/84504776-cf4d4c00-acbc-11ea-9f5d-aeedfc5f08af.png)

Below these lines I put the following code:

/*10 * * * node ~/Desktop/insta_reddit_bot-master/main.js >/dev/null 2>&1

But this didnt do anything. Also usign the frequencies listed in the example (9-18 18-9), instead of /*10, it didn't work.

Please help me :(

**Comment by FreekBes** [comment]
Hi there,

which Linux distribution are you on? Cron functionality could differ per distribution.

**Comment by Yannicko** [comment]
The most recent Ubuntu release within a Virtual Machine

**Comment by FreekBes** [comment]
Please take a look at this guide and let me know if it helps: https://www.digitalocean.com/community/tutorials/how-to-use-cron-to-automate-tasks-ubuntu-1804
