### ISSUE TITLE
hello sir , the bot working fine but the caption or the comment credit thing is working only sometimes.

### ISSUE THREAD

**Issue by shrimantagarain** [FreekBes/insta_reddit_bot#20]
the  comment credit thing is working only for 2-5 posts and thereafter I have to remove the cookies 
("rm handlers/cookies.json") to make it work again. is there any way to fix it?

**Comment by FreekBes** [comment]
Is the account you're running the bot on new? Did you just start running the bot? If so, this issue might resolve itself over time, when Instagram detects more logins/use from the bot.

What you could also do, is modify the caption's text in handlers/instagram.js (line 21 for comments or 177 for captions). Maybe the text has been used too much and is now on Instagram's blacklist for spam.

**Comment by shrimantagarain** [comment]
yes the account is new.........ok will try ur points! thankyou
