### ISSUE TITLE
Having an issue when running this code on windows

### ISSUE THREAD

**Issue by Jyqx** [FreekBes/insta_reddit_bot#22]
![image](https://user-images.githubusercontent.com/84685086/133872266-1a61ef95-2bf4-4b0a-b141-dec68c86e24a.png)

**Comment by FreekBes** [comment]
Hi there, does this issue occur with every post or just every now and then?

**Comment by Jyqx** [comment]
It happens every post and I can't get anything to post I'm not sure if I didn't set up it right but everything seems good in the settings.

**Comment by FreekBes** [comment]
Okay, that probably means there's something wrong with the way npm is set up or has installed dependencies. I suggest checking this StackOverflow thread and trying some of the things mentioned there: https://stackoverflow.com/questions/18419144/npm-not-working-read-econnreset

**Comment by Jyqx** [comment]
Okay thanks I'll try it now
