### ISSUE TITLE
getting these error

### ISSUE THREAD

**Issue by absolute-chad** [FreekBes/insta_reddit_bot#24]
null
(node:11884) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of null
    at D:\Softwares\mine\programming\Insta Bot\redi to insta poster\insta redi poster\bot.js:79:76
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11884) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11884) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by FreekBes** [comment]
Should be fixed now, thanks for reporting this issue!
