### ISSUE TITLE
Not familiar with this error but if anyone knows maybe we can fix these bugs together and make this a bomb ass bot.

### ISSUE THREAD

**Issue by scoopyw** [FreekBes/insta_reddit_bot#31]
Subreddit set to /r/strangerthings
Found a post to handle:
http://www.reddit.com//r/StrangerThings/comments/vdjtvo/clock_my_parents_got_oddly_looks_just_like_the/
Post added to done-list
Unable to handle post!
Selftext posts are not supported yet.
(node:409247) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'send' of undefined
    at Object.exports.sendSystemMessage (/home/ubuntu/stb/handlers/discordbot.js:123:61)
    at /home/ubuntu/stb/bot.js:77:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:409247) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:409247) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by scoopyw** [comment]
I believe though, this can be because of a post on reddit which doesn't include a picture or video. If this is true we could maybe implement an if else so it skips posts without pics or videos and continues to the next one with a pic or video in it.

**Comment by FreekBes** [comment]
Can you send me a copy of your configuration file `settings.json` (WITHOUT USERNAME AND PASSWORD)? I believe this has something to do with the Discord integeration.

**Comment by scoopyw** [comment]
`{
	"instagram": {
		"username": "",
		"password": "",
		"seed": "ikkomjeweltegen",
		"credits_in_caption": true,
		"credits_format": "Mirrored from a post on %subreddit% by %user%: %url%  #strangerthings #milliebobbybrown #finnwolfhard #noahschnapp #eleven #netflix #sadiesink #strangerthingsedit #gatenmatarazzo #calebmclaughlin #mikewheeler #st #mileven #strangerthingsedits #milliebobbybrownedit #millie #willbyers #edit #love #strangerthingsseason #florencebymills #mills #edits #fillie #it #riverdale #finnwolfhardedit #mbb #nillie #enolaholmes",
		"restart_every": 0
	},
	"reddit": {
		"subreddits": {
			"/r/strangerthings": 100
		}
	},
	"discord": {
		"enabled": false,
		"token": "ENTER_DISCORD_TOKEN_HERE_THEN_ENABLE",
		"prefix": "!",
		"channels": {
			"commands": "ENTER_CHANNEL_ID_HERE",
			"system": "ENTER_CHANNEL_ID_HERE"
		}
	},
	"schedule": {
		"human_error": {
			"min": 20,
			"max": 320
		},
		"hourly_timings": [
			[54],
			[],
			[],
			[32],
			[],
			[],
			[45],
			[],
			[],
			[34],
			[],
			[],
			[52],
			[],
			[],
			[25],
			[],
			[],
			[47],
			[20],
			[],
			[41],
			[],
			[],
			[32],
			[]
		]
	}
}`

**Comment by scoopyw** [comment]
```
{
	"instagram": {
		"username": "",
		"password": "",
		"seed": "ikkomjeweltegen",
		"credits_in_caption": true,
		"credits_format": "Mirrored from a post on %subreddit% by %user%: %url%  #strangerthings #milliebobbybrown #finnwolfhard #noahschnapp #eleven #netflix #sadiesink #strangerthingsedit #gatenmatarazzo #calebmclaughlin #mikewheeler #st #mileven #strangerthingsedits #milliebobbybrownedit #millie #willbyers #edit #love #strangerthingsseason #florencebymills #mills #edits #fillie #it #riverdale #finnwolfhardedit #mbb #nillie #enolaholmes",
		"restart_every": 0
	},
	"reddit": {
		"subreddits": {
			"/r/strangerthings": 100
		}
	},
	"discord": {
		"enabled": false,
		"token": "ENTER_DISCORD_TOKEN_HERE_THEN_ENABLE",
		"prefix": "!",
		"channels": {
			"commands": "ENTER_CHANNEL_ID_HERE",
			"system": "ENTER_CHANNEL_ID_HERE"
		}
	},
	"schedule": {
		"human_error": {
			"min": 20,
			"max": 320
		},
		"hourly_timings": [
			[54],
			[],
			[],
			[32],
			[],
			[],
			[45],
			[],
			[],
			[34],
			[],
			[],
			[52],
			[],
			[],
			[25],
			[],
			[],
			[47],
			[20],
			[],
			[41],
			[],
			[],
			[32],
			[]
		]
	}
}
```

**Comment by FreekBes** [comment]
Fixed the issue in the latest commit. Update the bot with `git pull` and this issue should no longer pop up. I cannot guarantuee other issues won't appear though, as I am no longer maintaining this repository.
