### ISSUE TITLE
The bot can't upload video's to IG

### ISSUE THREAD

**Issue by hugovantriet** [FreekBes/insta_reddit_bot#4]
I use your bot for a few days now and it works fine, exept the video function.
For some reason, the videos I submit to reddit are detected, but not ported to IG.
I got the logs [here](https://we.tl/t-jmBq0r2u6v).
I did not know where to contact you in the first place, so I also send you this issue on your IG DMs.

**Comment by FreekBes** [comment]
Could you reinitialize the whole repository to get rid of the cookies stored on your device for the bot?

To do this, copy your logindetails.json and the posts.json files to another location, then delete everything in the project folder. Redownload the repository, and run through the installation process once again. Place logindetails.json and posts.json back into the project folder afterwards, then run the bot for the first time.

Please let me know if this helps fix your problem.

**Comment by hugovantriet** [comment]
I don't know what the problem was, but after deleting the whole folder and reinstalling it, the bot works fine! Also with video. I got no idea what the problem was, because I installed the bot again in the same way as I did bevore. Thanks!
