### ISSUE TITLE
Crontab Questions

### ISSUE THREAD

**Issue by Yannicko** [FreekBes/insta_reddit_bot#5]
Hi! 
Thank's for your previous reply, however I now bought a Raspberry Pi and have a few questions about the Crontab:
- Do I still need to do node main.js once for the crontab to start working?
- Does crontab start working after you finish editing?
- Do I need to leave the command prompt / terminal open for crontab to work?
- Do you need to manually start anything or will the crontab do everything without needing 'a switch to be flipped'?

**Comment by FreekBes** [comment]
- no, once crontab is set up, you don't have to do anything.
- yes, once you quit the editor after running `crontab -e`, the new rules will become effective immediately.
- no, just make sure to keep the system running though! :)
- see the second answer
