### ISSUE TITLE
how to exclude NSFW posts

### ISSUE THREAD

**Issue by wanghaisheng** [FreekBes/insta_reddit_bot#6]

**Comment by FreekBes** [comment]
Posts marked as NSFW will already be skipped by the script, since most of them would never be allowed on Instagram anyways.

If it did post an image marked NSFW on your Instagram, the post probably wasn't marked as NSFW yet when the bot took a look at it.

**Comment by wanghaisheng** [comment]
@FreekBes 
how to check whether script run ?if use run.sh?

**Comment by FreekBes** [comment]
When running run.sh directly from a command line, the script should output some text, letting you know it's running.

When running run.sh using cron, there'll be no way of knowing whether or not it ran, apart from looking at the bot's Instagram account of course.

**Comment by wanghaisheng** [comment]
@FreekBes 
 directly from a command line  no output
account no post either

**Comment by wanghaisheng** [comment]
@FreekBes 
Failed to sign in!
IgCheckpointError: POST /api/v1/accounts/login/ - 400 Bad Request; challenge_required
    at Request.handleResponseError (/root/insta_reddit_bot/node_modules/instagram-private-api/dist/core/request.js:107:24)
    at Request.send (/root/insta_reddit_bot/node_modules/instagram-private-api/dist/core/request.js:53:28)
    at <anonymous>

**Comment by FreekBes** [comment]
You need to complete a login challenge. Sign in to the account on your phone or a computer, complete the challenge and then try again. If this keeps happening, try using the same network for both the computer running the script and the phone/computer you normally sign in to Instagram with. If that also fails, Instagram has blocked access to the account by the bot. I can help further in that case, but it's more complicated.

**Comment by wanghaisheng** [comment]
@FreekBes i have a server host a vpn service for myself to access ins.
first login ins through this vpn over chrome.there is challenge fixed.
then start bot on the server hosted vpn 

still 
Failed to sign in!
IgCheckpointError: POST /api/v1/accounts/login/ - 400 Bad Request; challenge_required
    at Request.handleResponseError (/root/offloaddogsboner_insta_reddit_bot/node_modules/instagram-private-api/dist/core/request.js:107:24)
    at Request.send (/root/offloaddogsboner_insta_reddit_bot/node_modules/instagram-private-api/dist/core/request.js:53:28)
    at <anonymous>

**Comment by FreekBes** [comment]
Then I cannot help you, sorry
